FROM debian:latest

RUN apt-get update && apt install -y gawk python debhelper devscripts build-essential vim dh-make help2man

WORKDIR /auter
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
