FROM centos:7

RUN yum update -y \
    && yum install -y git gcc rpm-build rpm-devel help2man \
    rpmlint make python bash coreutils diffutils patch rpmdevtools \
    && rpmdev-setuptree

WORKDIR /auter
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
